#This configuration file was written by: org.eclipse.equinox.internal.frameworkadmin.equinox.EquinoxFwConfigFileParser
#Tue Mar 24 15:41:27 KST 2026
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.39.0.202603170703
eclipse.p2.data.area=@config.dir/../p2/
eclipse.p2.profile=DefaultProfile
eclipse.product=org.springframework.boot.ide.branding.springtools
org.eclipse.equinox.simpleconfigurator.configUrl=file\:org.eclipse.equinox.simpleconfigurator/bundles.info
osgi.bundles=reference\:file\:org.eclipse.equinox.simpleconfigurator_1.5.700.v20251111-1031.jar@1\:start
osgi.bundles.defaultStartLevel=4
osgi.framework=file\:plugins/org.eclipse.osgi_3.24.100.v20251215-1416.jar
osgi.framework.extensions=reference\:file\:org.eclipse.osgi.compatibility.state_1.3.0.v20251022-1724.jar
osgi.instance.area.default=@user.home/Documents/workspace-spring-tools-for-eclipse-5.1.1.RELEASE
osgi.splashPath=platform\:/base/plugins/org.springframework.boot.ide.branding
